services:
  eureka-server:
    build: eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=default
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 10
    networks:
      - microservices-net

  gateway:
    build: gateway
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
    networks:
      - microservices-net

  companies-db:
    image: postgres:14-alpine
    container_name: companies-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: companies
      POSTGRES_PASSWORD: companies
      POSTGRES_DB: companies
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservices-net

  companies:
    build: companies
    container_name: companies
    ports:
      - "9091:9091"
    depends_on:
      - companies-db
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-net

  users-db:
    image: postgres:14-alpine
    container_name: users-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: users
      POSTGRES_DB: users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - microservices-net

  users:
    build: users
    container_name: users
    ports:
      - "9090:9090"
    depends_on:
      - users-db
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge