logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG

server:
  port: 8761  # Стандартный порт Eureka

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  # Сервер не регистрирует себя
    fetch-registry: true        # Сервер получает список сервисов