logging:
  level:
    org:
      springframework:
        web:
          client:
            RestTemplate: DEBUG
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE
#    apache:
#      http: DEBUG
#    httpclient:
#      wire: DEBUG

server:
  port: 9090

users:
  url: http://users:8080

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    show-sql: true
  sql:
    init:
      mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://companies-db:5432/companies
    username: companies
    password: companies
#    url: jdbc:postgresql://localhost:5432/users-companies
#    username: postgres
#    password: admin